language: php
php:
  - 7.2
before_script:
  - composer self-update
  - composer install
  - composer require php-coveralls/php-coveralls
script: phpunit
after_script:
  - php ./vendor/bin/php-coveralls -v
